### ISSUE TITLE
can not build an arm64-v8a bin  successfuly  on macos

### ISSUE THREAD

**Issue by alexlabs** [linebender/android_trace#16]
cat .cargo/config.toml 
[target.aarch64-linux-android]
ar = "/Users/stone/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar"
linker = "/Users/stone/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android27-clang"

build command: 
` cargo build --target aarch64-linux-android --release`

build error  with libc

**Comment by andreyfmc** [comment]
download
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by DJMcNab** [comment]
Thank you for your interest! Unfortunately, this issue is unactionable as is, because there's no information about what errors there are, or other failure modes.

I would suggest using cargo apk, rather than manually trying to setup the android support. `cargo ndk` might also work, but I've not tried it.

I'll close this, but will re-open if it becomes valid.

I've deleted the comment which was sent as it used a URL shortener, which I judged to be potentially a malware distribution attempt. If you can link to a trustworthy source instead, that would be helpful.
